trigger:
  batch: true
  branches:
    include:
      - "master"

variables:
- name: SolutionBaseName
  value: SFA.DAS.Forecasting
- name: BuildConfiguration
  value: release
- name: DACPACSolutionBaseName
  value: SFA.DAS.Forecasting.Database
- name: BuildPlatform
  value: any cpu
#- group: RELEASE Management Resources
#- group: RELEASE das-provide-feedback-employer
- name: Deploy
  value: $[or(eq(variables['Build.SourceBranch'], 'refs/heads/master'), eq(variables['Build.Reason'], 'Manual'), eq(variables['Build.Reason'], 'PullRequest'))]


resources:
  repositories:
  - repository: self
  - repository: das-platform-building-blocks
    type: github
    name: SkillsFundingAgency/das-platform-building-blocks
    ref: refs/tags/2.1.2
    endpoint: SkillsFundingAgency
  - repository: das-platform-automation
    type: github
    name: SkillsFundingAgency/das-platform-automation
    ref: refs/tags/5.1.5
    endpoint: SkillsFundingAgency
  pipelines:
  - pipeline: das-employer-config
    project: Digital Apprenticeship Service
    source: das-employer-config
    branch: master

stages:
- stage: Build
  jobs:
  - template: pipeline-templates/job/code-build.yml
    parameters:
      SolutionBaseName: $(SolutionBaseName)
      BuildConfiguration: $(BuildConfiguration)
  - template: azure-pipelines-templates/build/job/dacpac-template.yml@das-platform-building-blocks
    parameters:
      SolutionBaseName: $(DACPACSolutionBaseName)
      SqlProjectPath: src/$(DACPACSolutionBaseName)/$(DACPACSolutionBaseName).sqlproj