parameters:
  - name: ServiceConnection
  - name: SolutionBaseName
  - name: Environment
  - name: OverrideBlockOnPossibleDataLoss
    default: false
  - name: AppRoleAssignmentsServiceConnection
  - name: FunctionApps
    type: object
    default:
      - FunctionApp:
        Name: $(FunctionAppNameStandards)
        ProjectName: ApprenticeshipCourses
      - FunctionApp:
        Name: $(FunctionAppNameCommitments)
        ProjectName: Commitments
      - FunctionApp:
        Name: $(FunctionAppNameLevy)
        ProjectName: Levy
      - FunctionApp:
        Name: $(FunctionAppNamePayments)
        ProjectName: Payments
      - FunctionApp:
        Name: $(FunctionAppNamePreload)
        ProjectName: PreLoad
      - FunctionApp:
        Name: $(FunctionAppNameProjection)
        ProjectName: Projections
      - FunctionApp:
        Name: $(FunctionAppNameStub)
        ProjectName: StubApi


jobs:
- deployment: Deploy
  pool:
    name: DAS - Continuous Deployment Agents
  environment: ${{ parameters.Environment }}
  strategy:
    runOnce:
      deploy:
        steps:
        - template: azure-pipelines-templates/deploy/step/wait-azure-devops-deployment.yml@das-platform-building-blocks
          parameters:
            ServiceConnection: ${{ parameters.ServiceConnection }}
            EnvironmentId: $(Environment.Id)
            PipelineName: $(Build.DefinitionName)
            RunId: $(Build.BuildId)
        - template: azure-pipelines-templates/deploy/step/arm-deploy.yml@das-platform-building-blocks
          parameters:
            ServiceConnection: ${{ parameters.ServiceConnection }}
            SubscriptionId: $(SubscriptionId)
            Location: $(ResourceGroupLocation)
            Environment: ${{ parameters.Environment }}
            TemplatePath: $(Pipeline.Workspace)/${{ parameters.SolutionBaseName }}/azure/template.json
            ParametersPath: $(Pipeline.Workspace)/${{ parameters.SolutionBaseName }}/azure/template.parameters.json
            IsMultiRepoCheckout: true
            TemplateSecrets:
              LoggingRedisConnectionString: $(LoggingRedisConnectionString)
              ConfigurationStorageConnectionString: $(ConfigurationStorageConnectionString)
        - template: azure-pipelines-templates/deploy/step/generate-config.yml@das-platform-building-blocks
          parameters:
            EnvironmentName: $(EnvironmentName)
            ServiceConnection: ${{ parameters.ServiceConnection }}
            SourcePath: $(Pipeline.Workspace)/das-employer-config/Configuration/das-forecasting-tool
            StorageAccountName: $(ConfigurationStorageAccountName)
            StorageAccountResourceGroup: $(SharedEnvResourceGroup)
            TargetFileName: '*.schema.json'
            TableName: Configuration
            ConfigurationSecrets:
              PaymentsEventsApiClientSecret: $(PaymentsEventsApiClientSecret)
        - template: azure-pipelines-templates/deploy/step/app-role-assignments.yml@das-platform-building-blocks
          parameters:
            ServiceConnection: ${{ parameters.AppRoleAssignmentsServiceConnection }}
            ResourceName: $(FunctionAppNameCommitments)
            Tenant: $(Tenant)
            IsMultiRepoCheckout: true
        - template: azure-pipelines-templates/deploy/step/app-role-assignments.yml@das-platform-building-blocks
          parameters:
            ServiceConnection: ${{ parameters.AppRoleAssignmentsServiceConnection }}
            ResourceName: $(FunctionAppNamePreload)
            Tenant: $(Tenant)
            IsMultiRepoCheckout: true
        - template: azure-pipelines-templates/deploy/step/app-deploy.yml@das-platform-building-blocks
          parameters:
            ServiceConnection: ${{ parameters.ServiceConnection }}
            AppServiceName: $(AppServiceName)
            DeploymentPackagePath: $(Pipeline.Workspace)/${{ parameters.SolutionBaseName }}/${{ parameters.SolutionBaseName }}.Web.zip
        - ${{ each FunctionApp in parameters.FunctionApps }}:
          - template: azure-pipelines-templates/deploy/step/function-deploy.yml@das-platform-building-blocks
            parameters:
              ServiceConnection: ${{ parameters.ServiceConnection }}
              FunctionAppName: $({{ FunctionApp.Name }})
              DeploymentPackagePath: $(Pipeline.Workspace)/${{ parameters.SolutionBaseName }}/${{ parameters.SolutionBaseName }}.${{ FunctionApp.ProjectName}}.Functions.zip
        - template: azure-pipelines-templates/deploy/step/sql-dacpac-deploy.yml@das-platform-building-blocks
          parameters:
            AzureSubscription: ${{ parameters.ServiceConnection }}
            ServerName: $(SharedSQLServerFQDN)
            SqlUsername: $(SharedSQLServerUsername)
            SqlPassword: $(SharedSQLServerPassword)
            DacpacFile: $(Pipeline.Workspace)/DacpacArtifact/${{ parameters.SolutionBaseName }}/Database/bin/Release/SFA.DAS.Forecasting.Database.dacpac
            DatabaseName: $(DatabaseName)
            OverrideBlockOnPossibleDataLoss: ${{ parameters.OverrideBlockOnPossibleDataLoss }}
            Environment: ${{ parameters.Environment }}
