CREATE TABLE [dbo].[Balance]
(
	EmployerAccountId BIGINT NOT NULL IDENTITY,
	Amount DECIMAL NOT NULL,
	BalancePeriod DATETIME NOT NULL,
	ReceivedDate DATETIME NOT NULL CONSTRAINT DF_Balance__ReceivedDate DEFAULT (GETDATE()),
)